default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tracing_resilience_development

test:
  <<: *default
  database: tracing_resilience_test

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') { '' } %>
